'\" t
.\"     Title: adonis-clone
.\"    Author: Bobby Martin <bobb.mrtn@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 06/20/2013
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "ADONIS\-CLONE" "1" "06/20/2013" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
adonis-clone \- script to clone and use the adonis linux git repository
.SH "SYNOPSIS"
.sp
\fBadonis\-clone\fR [\fIOPTIONS\fR]
.SH "DESSCRIPTION"
.sp
The \fIadonis\-clone\fR(1) command automates the cloning of adonis linux packages by allowing you to simply provide the name of the package to clone\&. It also allows you to query the repository for a list of packages and descriptions\&. Lastly, it also allows you to query for specific data such as clone urls by specifying the neccessary fields\&. For a list of applicable fields, please consult the github API\&.
.SH "OPTIONS"
.PP
\fB\-h, \-\-help\fR
.RS 4
List all options available to
\fIadonis\-clone\fR\&.
.RE
.PP
\fB\-l, \-\-list\fR
.RS 4
List all packages available for cloning\&.
.RE
.PP
\fB\-d, \-\-descriptions\fR
.RS 4
List all packagess along with there description\&.
.RE
.PP
\fB\-p, \-\-property\fR
.RS 4
Get an attribute based on a github property\&.
.RE
.PP
\fB\-u, \-\-update\fR
.RS 4
Refresh the list of packages in the repository\&.
.RE
.PP
\fB\-c, \-\-clone\fR
.RS 4
Clone a package from the github repository\&.
.RE
.SH "COMMON USAGE EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
You want a list of all the packages available to clone\&.
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
$ adonis\-clone \-\-list
.fi
.if n \{\
.RE
.\}
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
You want to clone a package so you can work on it\&.
.RE
.sp
.if n \{\
.RS 4
.\}
.nf
$ adonis\-clone \-c adonis\-devscripts
.fi
.if n \{\
.RE
.\}
.sp
3\&.You need to refresh the list of available packages\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ adonis\-clone \-\-update
.fi
.if n \{\
.RE
.\}
.SH "AUTHORS"
.sp
This man page was written by Bobby Martin <\m[blue]\fBbobb\&.mrtn@gmail\&.com\fR\m[]\&\s-2\u[1]\d\s+2>\&. The current version of adonis\-devscripts was written by Bobby Martin\&.
.SH "COPYING"
.sp
Free use of this software is granted under the terms of the GNU General Public License (GPL) version 2\&.
.SH "AUTHOR"
.PP
\fBBobby Martin\fR <\&bobb\&.mrtn@gmail\&.com\&>
.RS 4
Author.
.RE
.SH "NOTES"
.IP " 1." 4
bobb.mrtn@gmail.com
.RS 4
\%mailto:bobb.mrtn@gmail.com
.RE
